#!/usr/bin/env bash
set -euo pipefail

mode="write"
if [ "${1:-}" = "--check" ]; then
  mode="check"
elif [ "$#" -ne 0 ]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

catalog="$(mktemp)"
output="$(mktemp)"
trap 'rm -f "$catalog" "$output"' EXIT

go run ./cmd/clyde help --json >"$catalog"

python3 - "$catalog" "$output" <<'PY'
import json
import re
import sys

catalog_path, output_path = sys.argv[1:]
with open(catalog_path, encoding="utf-8") as handle:
    catalog = json.load(handle)

def troff(value):
    value = re.sub(r"\b(?:Loom|Nora|NORA|Bram|Clyde)\b", lambda match: match[0].lower(), value)
    return value.replace("\\", "\\e").replace("-", "\\-")

lines = [
    '.\" Code-generated by .github/scripts/generate-man-page.sh; DO NOT EDIT.',
    f'.TH clyde 1 "" "clyde {troff(catalog["version"])}" "clyde Manual"',
    '.SH NAME',
    'clyde \\- local repository bundle review and NotebookLM sync harness',
    '.SH SYNOPSIS',
    '.B clyde',
    '.RI [ command ]',
    '.RI [ options ]',
    '.SH DESCRIPTION',
    'clyde prepares reviewable local repository bundles and uploads them to NotebookLM only after explicit approval.',
    'Run',
    r'.BR clyde\ doctor ,',
    'then',
    r'.BR clyde\ preview ,',
    'then',
    r'.BR clyde\ bundle ,',
    'then',
    r'.BR clyde\ sync\ --dry-run',
    'before approving an upload.',
    '.SH COMMANDS',
]

for command in catalog['commands']:
    lines.extend([
        '.TP',
        f'.B {troff(command["name"])}',
        troff(command['summary']),
        '.br',
        '.B Usage',
        '.nf',
        troff(command['syntax']),
        '.fi',
    ])

lines.extend([
    '.SH DOCUMENTATION',
    f'Full command help is available at {troff(catalog["help"])}.',
    r'.BR clyde\ help\ COMMAND',
    'prints command-specific help, and',
    r'.BR clyde\ help\ --json',
    'prints the machine-readable command catalog used to generate this manual.',
    '.SH SEE ALSO',
    troff(catalog['home']),
    '.br',
    troff(catalog['github']),
])

with open(output_path, 'w', encoding='ascii', newline='\n') as handle:
    handle.write('\n'.join(lines) + '\n')
PY

if [ "$mode" = "check" ]; then
  tr -d '\r' <docs/clyde.1 | cmp -s "$output" - || {
    echo "docs/clyde.1 is stale; run .github/scripts/generate-man-page.sh" >&2
    exit 1
  }
  exit 0
fi

cp "$output" docs/clyde.1
